// This file was autogenerated by C:\Users\Petr\Documents\WebGL-Earth\closure-library\closure\bin\build\depswriter.py.
// Please do not edit.
goog.addDependency('../../../we/debug.js', ['we.debug'], ['goog.debug.DivConsole', 'goog.debug.FancyWindow']);
goog.addDependency('../../../we/deps.js', [], []);
goog.addDependency('../../../we/gl/context.js', ['we.gl.Context'], ['WebGLDebugUtils', 'goog.array', 'goog.debug.Logger', 'goog.dom', 'goog.math.Matrix', 'we.debug']);
goog.addDependency('../../../we/gl/mesh.js', ['we.gl.Mesh'], []);
goog.addDependency('../../../we/gl/plane.js', ['we.gl.Plane'], ['goog.debug.Logger', 'we.debug', 'we.gl.Mesh']);
goog.addDependency('../../../we/gl/shader.js', ['we.gl.Shader'], ['goog.debug.Logger', 'goog.dom', 'we.gl.Context']);
goog.addDependency('../../../we/gl/texture.js', ['we.gl.Texture'], ['goog.debug.Logger']);
goog.addDependency('../../../we/init.js', ['we'], ['goog.Timer', 'goog.debug.ErrorHandler', 'goog.debug.Logger', 'goog.dom', 'goog.events', 'we.Scene', 'we.debug', 'we.gl.Context']);
goog.addDependency('../../../we/scene.js', ['we.Scene'], ['we.debug', 'we.gl.Context', 'we.gl.Plane', 'we.gl.Shader', 'we.gl.Texture']);
goog.addDependency('../../../we/webgl-debug.js', ['WebGLDebugUtils'], []);
